name: Python Tests

on: [push, pull_request]  # Acionar o workflow em push e pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Sistema operacional a ser usado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Baixar o código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2  # Configurar a versão do Python
      with:
        python-version: '3.12.4'  # Especifique a versão do Python desejada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-deps
        python -m spacy download pt_core_news_lg  # Baixar o modelo de língua portuguesa
        python -m nltk.downloader punkt
        
    - name: Run tests
      run: |
        pytest  # Executar os testes com pytest
