name: Python Tests and Code Quality

on: [push, pull_request]  # Acionar o workflow em push e pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Sistema operacional a ser usado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Baixar o código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2  # Configurar a versão do Python
      with:
        python-version: '3.12.4'  # Especifique a versão do Python desejada

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --no-deps
        python -m spacy download pt_core_news_lg  # Baixar o modelo de língua portuguesa
        python -m nltk.downloader punkt_tab

    - name: Run tests
      run: |
        pytest || echo "Tests failed, but continuing..."  # Executar os testes com pytest e continuar em caso de falha

  code_quality:
    runs-on: ubuntu-latest  # Sistema operacional a ser usado

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Baixar o código do repositório

    - name: Set up Python
      uses: actions/setup-python@v2  # Configurar a versão do Python
      with:
        python-version: '3.12.4'  # Especifique a versão do Python desejada

    - name: Install prospector
      run: |
        python -m pip install --upgrade pip
        pip install prospector  # Instalar o prospector

    - name: Run prospector for code quality analysis
      run: |
        # Executa o prospector e salva o status de retorno
        prospector || STATUS=$?
        
        # Checa se o status é 1 (erros de análise)
        if [[ "$STATUS" == "1" ]]; then
          echo "Prospector encontrou melhorias. Marcando como warning."
        elif [[ "$STATUS" -gt "1" ]]; then
          echo "Erro ao executar o prospector."
          exit 1  # Retorna erro se falha na execução
        fi
      continue-on-error: true  # Continua mesmo se o prospector retornar melhorias
